version: '3'

services:
  pump-bot:
    build: .
    container_name: telegram-pump-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      # Telegram 配置
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
      - TELEGRAM_ADMIN_IDS=${TELEGRAM_ADMIN_IDS}
      - TELEGRAM_SOURCE_CHAT_IDS=${TELEGRAM_SOURCE_CHAT_IDS}
      - TELEGRAM_TARGET_CHAT_IDS=${TELEGRAM_TARGET_CHAT_IDS}
      
      # 数据库连接
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://postgres:password@db:5432/pumpbot}
    networks:
      - bot-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: telegram-pump-bot-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-pumpbot}
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data: 