version: '3'

services:
  solana-bot:
    build: .
    container_name: telegram-solana-bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      # Telegram 配置
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_SESSION_STRING=${TELEGRAM_SESSION_STRING}
      - TELEGRAM_ADMIN_IDS=${TELEGRAM_ADMIN_IDS}
      - TELEGRAM_SOURCE_CHAT_IDS=${TELEGRAM_SOURCE_CHAT_IDS}
      - TELEGRAM_TARGET_CHAT_IDS=${TELEGRAM_TARGET_CHAT_IDS}
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 